import assert from 'node:assert/strict';
import { Vector3, Scene, PerspectiveCamera } from '../src/engine/index.js';
import { liftCar, stepFlyingCar, FLIGHT_TUNING } from '../src/exploration/FlyingCar.js';
import { Traffic } from '../src/exploration/Traffic.js';
import { makeCar } from '../src/exploration/CarModel.js';
import { Colliders } from '../src/world/Colliders.js';

const flat={floor:()=>10.11,clearance:()=>16,collide:()=>false};
const make=()=>({position:new Vector3(0,10.11,0),heading:0,speed:20,pitch:0,roll:0,steer:0});
let car=make();liftCar(car);
stepFlyingCar(car,1/60,{throttle:1},flat);
assert.ok(car.position.y>10.11&&car.position.y<10.3,'takeoff rises smoothly');
assert.ok(car.speed>=20,'takeoff preserves forward momentum');
for(let i=0;i<600;i++)stepFlyingCar(car,1/60,{throttle:1,boost:true},flat);
assert.ok(car.speed>FLIGHT_TUNING.maxSpeed&&car.speed<=FLIGHT_TUNING.boostSpeed);
assert.ok(car.position.y>17.9&&car.position.y<19,'neutral controls settle into a hover');
const before=car.position.y;
for(let i=0;i<120;i++)stepFlyingCar(car,1/60,{vertical:1},flat);
assert.ok(car.position.y>before+25,'Space climbs');
for(let i=0;i<180;i++)stepFlyingCar(car,1/60,{vertical:-1},flat);
assert.ok(car.position.y>=10.11,'descent never crosses the ground');
const heading=car.heading;for(let i=0;i<120;i++)stepFlyingCar(car,1/60,{steer:-1},flat);
assert.ok(car.heading<heading-1.5,'flight steering turns the same way as driving');

car=make();car.position.y=50;liftCar(car);car.flight.takeoffY=null;
for(let i=0;i<180;i++)stepFlyingCar(car,1/60,{throttle:1,boost:true},{...flat,collide:(_x,_y,z)=>z>15});
assert.ok(car.position.z<=15,'high-speed flight cannot tunnel through a building');
const ceiling=car.position.y+.5;
for(let i=0;i<120;i++)stepFlyingCar(car,1/60,{vertical:1},{...flat,collide:(_x,y)=>y>ceiling});
assert.ok(car.position.y<=ceiling,'climbing cannot tunnel through a ceiling');

car=make();car.position.y=65;liftCar(car);car.flight={...car.flight,phase:'landing',target:new Vector3(18,10.11,12)};
let landed=false;
for(let i=0;i<900&&!landed;i++)landed=stepFlyingCar(car,1/60,{},flat);
assert.ok(landed&&car.motion.grounded&&!car.flight,'assisted landing returns control to the wheels');
assert.ok(car.position.distanceTo(new Vector3(18,10.11,12))<.001);
console.log('ok smooth takeoff, momentum, hover, boost, altitude controls, swept walls/ceilings and landing');

const keys=new Set(),messages=[],terrain={size:10000,heightAt:()=>10,groundHeight:()=>10};
const colliders=new Colliders(),player={mode:'walk',position:new Vector3(0,10,3),velocity:new Vector3()};
const route={nearest:(x,z)=>({s:z,distance:Math.abs(x)}),sample:s=>({x:0,z:s,y:10,heading:0,s})};
const app={scene:new Scene(),terrainData:terrain,colliders,player,camera:new PerspectiveCamera(),input:{enabled:true,down:k=>keys.has(k),consumeLook:()=>({x:0,y:0})},game:{cancelLine(){},rod:{equip(){}},toast:s=>messages.push(s)},boatCtl:{driven:false},exploration:{plane:{group:{}},closeDialogue(){},toggleJournal(){},vehicles:{available:true}}};
const traffic=Object.create(Traffic.prototype);
Object.assign(traffic,{app,terrain,route,cars:[],active:null,time:0,cameraPosition:new Vector3(),cameraTarget:new Vector3(),orbit:0,orbitPitch:.32,populate(){},planReturn:()=>[]});
app.exploration.traffic=traffic;
const model=makeCar(1);
car={...model,id:0,route,position:model.group.position,heading:0,speed:0,pitch:0,roll:0,steer:0,spin:0,s:0,direction:1,wait:0,retry:0};
car.position.set(0,10.11,0);car.collider=colliders.addBox(new Vector3(0,10.96,0),new Vector3(.95,.8,2.15),0,{tag:'traffic:0'});
traffic.cars.push(car);app.scene.add(car.group);
assert.ok(traffic.enter(car));
const rack=colliders.addBox(new Vector3(0,13.5,0),new Vector3(1,.1,2));
assert.equal(traffic.toggleFlight(),false,'a low ceiling prevents takeoff without losing driving control');assert.ok(!car.flight);assert.equal(traffic.active,car);
assert.ok(await traffic.summon());assert.ok(Math.hypot(car.position.x,car.position.z)>3,'recall checks the entire car beneath low props');
rack.solid=false;assert.ok(traffic.toggleFlight());
for(let i=0;i<150;i++)traffic.update(1/60);
assert.equal(player.mode,'car');assert.equal(traffic.active,car);assert.ok(car.position.y>17);
assert.ok(car.magic.visible&&car.wheels.every(w=>Math.abs(w.pivot.rotation.z)>.6),'enchanted cars glow and fold their wheels');
const frozen=car.position.clone();traffic.update(.05,true);
assert.ok(car.position.distanceTo(frozen)<1e-8,'paused flight does not snap to the road');
app.input.enabled=false;traffic.update(.05);assert.ok(car.position.distanceTo(frozen)<1e-8);assert.equal(traffic.toggleFlight(),false);app.input.enabled=true;
app.input.captured=true;assert.equal(traffic.toggleFlight(),false,'map capture prevents a flight toggle');app.input.captured=false;
assert.ok(traffic.toggleFlight());assert.equal(car.flight.phase,'landing');
assert.ok(traffic.toggleFlight());assert.equal(car.flight.phase,'flying','F cancels landing');
terrain.heightAt=terrain.groundHeight=()=>-20;
const ocean=car.position.clone();assert.equal(traffic.exit(),false,'no midair exit above water');assert.equal(traffic.active,car);assert.ok(car.position.distanceTo(ocean)<1e-8);assert.equal(car.flight.phase,'flying');
terrain.heightAt=terrain.groundHeight=()=>10;
const wall=colliders.addBox(new Vector3(0,20,0),new Vector3(100,20,100));
assert.equal(traffic.toggleFlight(),false,'blocked landing keeps flying');assert.equal(car.flight.phase,'flying');wall.solid=false;
assert.ok(traffic.exit());assert.equal(player.mode,'car','E keeps the player inside until touchdown');
for(let i=0;i<900&&traffic.active;i++)traffic.update(1/60);
assert.equal(traffic.active,null);assert.equal(player.mode,'walk');assert.ok(player.position.distanceTo(car.position)>2,'auto-exit position is not overwritten by the flight update');
assert.ok(!car.flight&&car.motion===null);assert.ok(!car.playerDriver.visible);
assert.ok(traffic.enter(car));assert.ok(traffic.toggleFlight());for(let i=0;i<150;i++)traffic.update(1/60);
const released=car.position.y;traffic.release();traffic.update(1/60);
assert.ok(car.position.y>released-1,'mode switches leave the unoccupied car descending smoothly');
for(let i=0;i<900&&car.flight;i++)traffic.update(1/60);
assert.ok(!car.flight,'the local driver lands after switching away');
player.mode='walk';player.position.copy(car.position);assert.ok(traffic.enter(car));assert.ok(traffic.toggleFlight());for(let i=0;i<150;i++)traffic.update(1/60);
assert.ok(await traffic.summon());assert.equal(car.flight,null,'4 clears flight state when recalling the car');traffic.update(1/60);
assert.equal(player.mode,'car');assert.ok(car.motion.grounded);
assert.ok(traffic.toggleFlight());terrain.heightAt=terrain.groundHeight=()=>-20;
assert.equal(await traffic.summon(),false,'failed recall preserves the current flying car');assert.equal(traffic.active,car);assert.ok(car.flight);
terrain.heightAt=terrain.groundHeight=()=>10;
car.setFlight(0);assert.ok(!car.magic.visible&&car.wheels.every(w=>w.pivot.rotation.z===0&&w.pivot.position.y===.365));
car.dispose();
console.log('ok same-car ownership, magic visuals, pause/map capture, cancel landing, water/blocked refusal, E auto-exit and driver landing');
